language: csharp
solution: TestProj.sln
    
jobs:
  include:
    - stage: GitHub Release
      script: echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        api_key: 8cb0d74a220c869f32d9f37f2568ee255f8b0b50
        skip_cleanup: true
        on:
          tags: true